### ISSUE TITLE
setWeekArrayType无效啊

### ISSUE THREAD

**Issue by dengxingwen** [MagicMashRoom/SuperCalendar#101]
1.周日为第一天        
calendarAdapter.setWeekArrayType(CalendarAttr.WeekArrayType.Sunday);
这样设置无效；

2.看很多人设置WeekArrayType = 1，我怎么设置不了；

**Comment by MagicMashRoom** [comment]
v1.5.0已经修改了

**Comment by dengxingwen** [comment]
看了下你demo里面也设置了这个calendarAdapter.setWeekArrayType(CalendarAttr.WeekArrayType.Sunday);
也是没有效果啊
