### ISSUE TITLE
第一次初始化为CalendarType.WEEK周模式

### ISSUE THREAD

**Issue by alex2390** [MagicMashRoom/SuperCalendar#105]
CustomDayView customDayView = new CustomDayView(context, R.layout.custom_day);
        calendarAdapter = new CalendarViewAdapter(
                context,
                onSelectDateListener,
                CalendarAttr.CalendarType.WEEK,
                CalendarAttr.WeekArrayType.Sunday,
                customDayView);
这样设置怎么无效呢

**Comment by MagicMashRoom** [comment]
需要在view 显示出来后 手动调用Utils.scrollToWeek方法

**Comment by fenggeZhang** [comment]
设置周模式之后，但是显示的周并不是选中的周？请问怎么弄？
