### ISSUE TITLE
如何添加一种新的显示状态

### ISSUE THREAD

**Issue by DeveloperHu** [MagicMashRoom/SuperCalendar#106]
如State里面添加一个green  然后日历可以根据state来改变日历某一天或某一段时间的背景颜色
希望大大能说说

**Comment by alex2390** [comment]
demo的CustomDayView中有设置颜色的方法，
 private void renderSelect(State state) {
        if (state == State.SELECT) {
            selectedBackground.setVisibility(VISIBLE);
            dateTv.setTextColor(Color.WHITE);
        } else if (state == State.NEXT_MONTH || state == State.PAST_MONTH) {
            selectedBackground.setVisibility(GONE);
            dateTv.setTextColor(Color.parseColor("#d5d5d5"));
        } else {
            selectedBackground.setVisibility(GONE);
            dateTv.setTextColor(Color.parseColor("#111111"));
        }
    }

    private void renderToday(CalendarDate date) {
        if (date != null) {
            if (date.equals(today)) {
                dateTv.setText("今");
                todayBackground.setVisibility(VISIBLE);
            } else {
                dateTv.setText(date.day + "");
                todayBackground.setVisibility(GONE);
            }
        }
    }

**Comment by DeveloperHu** [comment]
我想的是，例如“2018-1-3”到“2018-1-7”这段时间给它一个圆角绿色背景，这种是新的state，我应该在哪里改，才能有这种自定义的效果？？

**Comment by MagicMashRoom** [comment]
判断日期然后给dateTV设置背景

**Comment by DeveloperHu** [comment]
Thanks♪(･ω･)ﾉ
