### ISSUE TITLE
日期比星期像右位移了一位

### ISSUE THREAD

**Issue by PrometNexus** [MagicMashRoom/SuperCalendar#110]
18年1月1日是周一，而显示出来的是周二，整体都往后移了一位，这种当前月第一天刚好是本周第一天的情况，填充月中周数据的fillWeek方法中单元格却是从0开始记位的，所以本月第一天单元格记录为上一月的数据了，减掉1可以变正常，但切换周模式还是之前的错误情况，不知道怎么改。

**Comment by dengxingwen** [comment]
在初始化的时候你要指定每周的第一天是周一还是周天，要设置的；
calendarAdapter = new CalendarViewAdapter(
context,
onSelectDateListener,
CalendarAttr.CalendarType.WEEK,
CalendarAttr.WeekArrayType.Sunday,
customDayView);
//
如果你想让周日为第一天 就设置WeekArrayType.Sunday，如果周一为第一天就设置为WeekArrayType.Monday
