### ISSUE TITLE
Max and Min date range

### ISSUE THREAD

**Issue by monowar1993** [MagicMashRoom/SuperCalendar#132]
Hello
Is there an way to add max and min date range? Also how can I jump to a specific date?

**Comment by adrianpop1990** [comment]
You can select a date like this:
```kotlin
     /**
     * Should only be called, when view is inflated and visible (e.g. determine by focus).
     */
    private fun selectToday() {
        val today = SuperCalendarDate()
        mCalendarAdapter.notifyDataChanged(today)
    }
```

**Comment by monowar1993** [comment]
It going to today. But what I want to go to 22-10-2016

**Comment by monowar1993** [comment]
@adrianpop1990 is there any way to set and get max and min year.

**Comment by adrianpop1990** [comment]
If you want to select the date 22-10-2016, you can use this:
```kotlin
/*
 * Should only be called, when view is inflated and visible (e.g. determine by focus).
 */
private fun selectToday() {
    val today = SuperCalendarDate(2016, 10, 22)
    mCalendarAdapter.notifyDataChanged(today)
}
```

> is there any way to set and get max and min year.
I don't saw any method to set or get the max and min year.
If you need this feature, you can create a fork and implement it.
The structure of the calendar is easy to understand, so it should not be hard to do this.
