### ISSUE TITLE
切换日时，数据可以刷新吗

### ISSUE THREAD

**Issue by LittleWaver** [MagicMashRoom/SuperCalendar#14]
切换日时，有刷新数据的接口吗

**Comment by MagicMashRoom** [comment]
onSelectDateListener = new OnSelectDateListener() {
            @Override
            public void onSelectDate(CalendarDate date) {
                refreshClickDate(date);
            }

            @Override
            public void onSelectOtherMonth(int offset) {
                //偏移量 -1表示上一个月 ， 1表示下一个月
                monthPager.selectOtherMonth(offset);
            }
        };
example中 SyllabusActivity  中的onSelectDateListener就是这个作用 
你应该仔细看看代码 所有的功能都再代码里 我不是产品文档
