### ISSUE TITLE
为什么这个样子呢

### ISSUE THREAD

**Issue by alguojian** [MagicMashRoom/SuperCalendar#149]
![518663808d30476fa3eda0972513eda2](https://user-images.githubusercontent.com/29728638/38492454-87c57e9c-3c21-11e8-9051-552373621854.jpg)

**Comment by alguojian** [comment]
有人回复我一下嘛

**Comment by jinxijun** [comment]
CalendarViewAdapter文件中
calendarAttr.setCalendarType(CalendarAttr.CalendarType.MONTH);//这里设置成month就好了

**Comment by alguojian** [comment]
好的，谢谢
