### ISSUE TITLE
Demo上周日历和月日历同时显示出来了

### ISSUE THREAD

**Issue by wardenlzr** [MagicMashRoom/SuperCalendar#157]
![image](https://user-images.githubusercontent.com/16572346/40035431-5222aa38-5834-11e8-92a3-d527d5102d02.png)

运行demo随便点一个日期出现如图所示，请问显示月日历时怎样默认隐藏掉周日历？

**Comment by Anurag--Singh** [comment]
Yest, it happens same for me not every time but frequently.

**Comment by ITzhangyan** [comment]
@wardenlzr 请问你解决了么

**Comment by wardenlzr** [comment]
@ITzhangyan 
CalendarViewAdapter中
`private void init(Context context, OnSelectDateListener onSelectDateListener) {
        saveSelectedDate(new CalendarDate());
        //初始化的种子日期为今天
        seedDate = new CalendarDate();
        for (int i = 0; i < 3; i++) {
            CalendarAttr calendarAttr = new CalendarAttr();
            //CalendarAttr.CalendarType.WEEK 这是原来的参数
            calendarAttr.setCalendarType(CalendarAttr.CalendarType.MONTH);
            calendarAttr.setWeekArrayType(weekArrayType);
            Calendar calendar = new Calendar(context, onSelectDateListener, calendarAttr);
            calendar.setOnAdapterSelectListener(new OnAdapterSelectListener() {
                @Override
                public void cancelSelectState() {
                    cancelOtherSelectState();
                }

                @Override
                public void updateSelectState() {
                    invalidateCurrentCalendar();
                }
            });
            calendars.add(calendar);
        }
    }`
