### ISSUE TITLE
是否可以添加日期多選功能

### ISSUE THREAD

**Issue by eimori** [MagicMashRoom/SuperCalendar#19]
如題，可否在該套件添加多選的功能呢
或是能否告知可以從哪邊著手修改

**Comment by MagicMashRoom** [comment]
在Calendar的onClickDate处的onSelectedAdapterListener.cancelAllClickState这句话取消掉

**Comment by eimori** [comment]
您好，關於您說的設置，我在程式碼裡面沒有看到
能請您再確認看看嗎？

**Comment by MagicMashRoom** [comment]
calendar的88至90行

**Comment by MagicMashRoom** [comment]
你是台湾人？

**Comment by eimori** [comment]
是的
我確認一下，謝謝
