### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DalyLee** [MagicMashRoom/SuperCalendar#2]
1.点击切换周月视图   list有留白，效果图:

![2](https://user-images.githubusercontent.com/22758905/27506575-5881e55c-58ed-11e7-9d88-58389c6529db.png)

2.切换周月后，点击list某一子item,再次随便连续选择某一日期，日历有多选，控件日期重复显示，效果图:

![1](https://user-images.githubusercontent.com/22758905/27506563-f589afac-58ec-11e7-8f7f-fe8e976733e8.png)

7.0测试
@MagicMashRoom 

- [ ]

**Comment by MagicMashRoom** [comment]
已修改 是因为对MonthPager的高度计算出错导致的
