### ISSUE TITLE
recycleview 把日历覆盖了一些

### ISSUE THREAD

**Issue by wlianghe00** [MagicMashRoom/SuperCalendar#22]
![image](https://user-images.githubusercontent.com/3353880/28660791-0a45098c-72e7-11e7-8d47-d4e86dcb7a09.png)
这个是什么原因啊

**Comment by MagicMashRoom** [comment]
recyclerView 设置成matchparent readme里有指出

**Comment by wlianghe00** [comment]
@MagicMashRoom 是match_parent啊
<android.support.design.widget.CoordinatorLayout
                android:id="@+id/content"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_weight="1">

                <com.isat.ehealth.ui.widget.calendar.view.MonthPager
                    android:id="@+id/calendar_view"
                    android:layout_width="match_parent"
                    android:layout_height="270dp"
                    android:background="#fff" />

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/recycler"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="#ffffff"
                    app:layout_behavior="com.isat.ehealth.ui.widget.calendar.behavior.RecyclerViewBehavior"
                    android:layout_gravity="bottom"
                    android:clipToPadding="false"
                    android:clipChildren="false"
                    android:layout_marginBottom="45dp"/>
                
                
                
            </android.support.design.widget.CoordinatorLayout>

**Comment by MagicMashRoom** [comment]
那recyclerView得高度为什么只有wrapcontent那么高？
你把CoordinatorLayout的layout_weight属性取消掉
你运行我的DEMO时会出现这种情况吗？

**Comment by MagicMashRoom** [comment]
或者你给recyclerView设置一个固定的高度尝试一下是什么问题

**Comment by MagicMashRoom** [comment]
这个应该不是日历控件的内部问题 就是recyclerView高度的问题 必须使recyclerView 设置成matchparent
才能遮住后面的日历

**Comment by wlianghe00** [comment]
![image](https://user-images.githubusercontent.com/3353880/28661665-ff87e1ce-72e9-11e7-8aee-8d966bf372b6.png)
你的demo是好的。。。。。刚刚是父布局没有设置match_parent,现在改成match_parent 就全部遮挡了

**Comment by MagicMashRoom** [comment]
那你按我的DEMO来  DEMO怎么写 你就怎么写 你怎么问我我也不知道你什么问题 你这样描述问题我没有办法分析  先自己看代码解决

**Comment by wlianghe00** [comment]
![image](https://user-images.githubusercontent.com/3353880/28663690-a7cb1580-72f0-11e7-9855-e3e171f7ed50.png)

你的demo把这里屏蔽就会出现这个问题，这2个textview怎么会有影响呢？
