### ISSUE TITLE
fix(1、周月切换问题；2、recyclerview反弹)

### ISSUE THREAD

**Issue by xuwab** [MagicMashRoom/SuperCalendar#23]
1、例如点击上个月某一天后，切换回当前月，月切换周，再周切换月，切换回上个月执行月切换周，显示有问题；
2、下拉时，日历下的recyclerview内容下拉会出现反弹，部分内容嵌入日历。导致想上拉日历得重新下拉全部内容后，才可以上拉日历。可否在日历内根据上下拉手势实现日历的周月切换。

**Comment by MagicMashRoom** [comment]
已修复

**Comment by MagicMashRoom** [comment]
重新下载代码
