### ISSUE TITLE
添加两个按钮手动跳转月份，但是跳转了一个月份后就不会动了

### ISSUE THREAD

**Issue by lijunyandev** [MagicMashRoom/SuperCalendar#25]
有一个需求，两个向左向右的箭头，点击分别跳转到上一月下一月，我分别设置了monthPager.selectOtherMonth(int);-1和1，效果是第一次跳转正常，第二次会抖动一下，但是跳不过去。这个需求应该很普遍吧，是我使用方式不对还是怎么滴？

**Comment by MagicMashRoom** [comment]
应该是使用setCurrentIndex(getCurrentPosition -1) 或+1

**Comment by lijunyandev** [comment]
你好，monthPager没有这个方法，有setRowIndex,setCurrentItem,setCurrentPosition试了都没有效果，而且后两个还会ANR

**Comment by lijunyandev** [comment]
你好，请问这个是可以设置的吗？你那边有什么办法吗？

**Comment by MagicMashRoom** [comment]
不知道干什么的方法不要乱用 看方法名的意思setRowIndex setCurrentPosition这明显不是修改MonthPager的页数的方法
monthPager.setCurrentItem(monthPager.getCurrentPosition() - 1);这个方法可以使用

**Comment by MagicMashRoom** [comment]
重新下载一下DEMO看一下

**Comment by lijunyandev** [comment]
好的，谢谢你，已经可以了。但是“不知道干什么的方法不要乱用”这话不敢苟同，学习调试的时候不试试怎么知道效果呢，开发阶段方法调用一下右不会搞坏。我只是想试试看它的效果。【抱拳】

**Comment by MagicMashRoom** [comment]
setRowIndex setCurrentPosition 你根据英文的意思 或者你跟进去看一下方法内部是什么 是不是可以减少你的调试次数 不知道这个方法不要乱用 就是要让你理解了这个方法之后再用 如果你的方法都是通过试出来的 那么也就是说程序的实现对你来说都是黑盒的 即使是实现了需求又有什么用呢
