### ISSUE TITLE
关于 周 功能

### ISSUE THREAD

**Issue by zongyao2** [MagicMashRoom/SuperCalendar#3]
是否可考虑新增以下 2 个功能：
1、切换到周滚动时，提供显示当前周是当年的第几周
2、根据选择哪年哪周，再跳转滚动到该周的周日历
谢谢~

**Comment by MagicMashRoom** [comment]
关于第一个问题 你使用CalendarAdapter的getSeedDate方法得到日期 然后通过java.calendar的api计算就好了

**Comment by MagicMashRoom** [comment]
关于第二个问题 你新建一个日期实例 这个日期是你选择的那一年的那一周的某一天 然后 在使用CalendarAdapter.notifyDataChange方法就直接跳转过去了

**Comment by MagicMashRoom** [comment]
关于第一个问题描述有错误 你可以通过CalendarAdapter.getItem.get(currentPosition).getSeedDate得到一个日期对象 然后再调用calendar的api

**Comment by MagicMashRoom** [comment]
好吧 我周末给你开放出相关的api 让你直接通过monthpager的实例直接得到当前显示的日期 你可以通过日期在计算出是第几周

**Comment by MagicMashRoom** [comment]
跳转到指定周我不会再给你开放api了  notifydatachange方法已经可以了 至于你怎么设计这个选择器 是你的事了 加油
