### ISSUE TITLE
切换周月bug和RecyclerView显示不全bug及功能扩展

### ISSUE THREAD

**Issue by ixiangfeng** [MagicMashRoom/SuperCalendar#31]
1.当RecyclerView滑动到底时再切换周月时，滑动切换周月不正常，RecyclerView显示不全
2.当RecyclerView内容不足一屏时滑动切换为周模式不正常（选中周跳到上面，下面空白，放弃切换时显示不正常）
3.如何像小米日历那样滑动日历部分也可以切换周月（当前只有滑动RecyclerView才可以切换）

**Comment by MagicMashRoom** [comment]
目前在切换周月模式或者切换日期的时候不能进行另外的操作 因为会造成数据的混乱

**Comment by awq14789** [comment]
请问第二个问题怎么弄？@ixiangfeng @MagicMashRoom
![图片](http://ww2.sinaimg.cn/large/0060lm7Tly1fjdcw55flaj30k00zk75h.jpg)

**Comment by awq14789** [comment]
请问第二个问题你是怎么解决的？ @ixiangfeng
