### ISSUE TITLE
想问下 怎么才能实现 不用滑动下面的Recyclerview 上下滑动日历就可以控制日历周月切换啊 ..

### ISSUE THREAD

**Issue by ynpl** [MagicMashRoom/SuperCalendar#32]
想问下 怎么才能实现 不用滑动下面的Recyclerview 上下滑动日历就可以控制日历周月切换啊 ..

**Comment by ixiangfeng** [comment]
我看了下小米的日历上下滑动日历部分也是可以的，想了下可以在Calendar的onTouchEvent处理，代码还没理清楚，不知道还有没有别的方法，还有把RecyclerView改用系统的Behavior滑动很自然，楼主的估计还可以改善下

**Comment by ynpl** [comment]
@MagicMashRoom

**Comment by HelloWym** [comment]
我也想问这个问题，怎么才能实现 不用滑动下面的Recyclerview 上下滑动日历就可以控制日历周月切换啊 ..

**Comment by MagicMashRoom** [comment]
项目实现的机制是利用了协调布局 coordinatelayout 如果想让上半部分的布局也会触发周月日历切换的话 也应该利用到协调布局 这个我还没有实现 各位如果有时间可以尝试一下
