### ISSUE TITLE
同是道中人

### ISSUE THREAD

**Issue by liuhonghao1994** [MagicMashRoom/SuperCalendar#35]
你好，楼主，你的公司是教育项目和我们公司一样，产品方向也一样，能给个联系方式么，有问题方便沟通

**Comment by zhenghaoyang** [comment]
![image](https://user-images.githubusercontent.com/10669036/29051616-8b5c132a-7c16-11e7-937b-97f7cb3a93c1.png)
最底下这一行显得多余了，怎么解决
