### ISSUE TITLE
底部这一行显得多余了

### ISSUE THREAD

**Issue by zhenghaoyang** [MagicMashRoom/SuperCalendar#36]
![image](https://user-images.githubusercontent.com/10669036/29051725-497dbd18-7c17-11e7-91a2-d77d11ab8c3e.png)
如何解决

**Comment by a1227308812** [comment]
不多余啊，你想想如果这个月的1号是在星期日你就必须要6行显示了，不然你看你自己手机上面的日历，也是一样的。

**Comment by ixiangfeng** [comment]
有时会在下面一行的，还有一种是把高度动态分成五行或六行

**Comment by zhenghaoyang** [comment]
我想要的是固定只显示五行

**Comment by ixiangfeng** [comment]
固定5行那你31 30号不要了？

**Comment by zhenghaoyang** [comment]
哈哈，尴尬了。我回去看了一下，我要的效果，确实是你说的那个动态五六行。而不是我以为的固定五行。

**Comment by jinhui1314** [comment]
@zhenghaoyang 哥们动态的五六行实现了么

**Comment by zhenghaoyang** [comment]
五六行，这个Demo已经实现了

**Comment by zhenghaoyang** [comment]
@jinhui1314 五六行，这个Demo已经实现了

**Comment by jinhui1314** [comment]
@zhenghaoyang 已经实现了？项目直接运行就可以动态显示五六行，还是需要自己调用一些方法设置
