### ISSUE TITLE
日历模式控制问题

### ISSUE THREAD

**Issue by a1227308812** [MagicMashRoom/SuperCalendar#37]
楼主，我想不用recycler的上下滑动来关联日历的月，周模式。想用一个自己的view，但是现在我现在在自定义的日历控件和recycler控件中间加上一个自己的view时，
![image](https://user-images.githubusercontent.com/21053292/29107539-3eae2732-7d0d-11e7-95d1-8bc4b60bb203.png)
但是最后显示的时候这个位置不对啊，是这样的

![c86c6bacb3f026f04cf54eb543c2960e](https://user-images.githubusercontent.com/21053292/29107787-6b453686-7d0e-11e7-85f7-cf01712cbf74.jpg)

我想把这个textview放到日历控件和recycler控件之间，然后通过添加的这个textview来控制日历的显示模式，楼主请帮忙看看呢！给条明路

**Comment by MagicMashRoom** [comment]
你需要了解协调布局的特性 不在使用recyclerView作为协调布局的dependence

**Comment by ma969070578** [comment]
解决了吗？ 我也有这需求~
