### ISSUE TITLE
定位到今天的日期的问题

### ISSUE THREAD

**Issue by jannonx** [MagicMashRoom/SuperCalendar#38]
example 无法定位到当前月的当前日期，只会跳转到所在当前月的页面的对应日期

**Comment by MagicMashRoom** [comment]
啥意思

**Comment by jannonx** [comment]
比如今天是8月11号，我在当前月的页面，然后选择除了今天的日期，点击“今天”按钮，可以跳到今天的日期。但是，我在其他月的页面，比如9月，点击“今天”按钮，会跳到9月11号，而不会跳到8月11号。

**Comment by MagicMashRoom** [comment]
左上角的日期忘了更新
