### ISSUE TITLE
Demo打开的时候没法自动显示日历么？

### ISSUE THREAD

**Issue by WenheLI** [MagicMashRoom/SuperCalendar#39]
Demo启动后需要点 上／下月或者switch的button 才能让calendar显示出来 这是系统版本的问题么？
系统7.1.1 and 8.0

**Comment by ma969070578** [comment]
可能是部分手机由于禁用硬件加速，造成draw()方法 无效

在调用的Activity 添加  android:hardwareAccelerated="true"

**Comment by MagicMashRoom** [comment]
请在onWindowFocusChanged或者确定view已经出现的生命周期后调用refreshCalendar方法
