### ISSUE TITLE
快速滑动RecyclerView从月模式划到周模式后，RecyclerView仍会滑动到底部。

### ISSUE THREAD

**Issue by liujia95** [MagicMashRoom/SuperCalendar#41]
而且有时候来回快速滑动会出现：显示的是月模式，但是上滑RecyclerView并不能把月模式转化为周模式，要把RecyclerView上滑到顶部，才能正常的控制月周模式切换的动画。

**Comment by fuyifang** [comment]
大神这个问题解决了么？
