### ISSUE TITLE
DialogFragment中使用该控件问题

### ISSUE THREAD

**Issue by loveanao** [MagicMashRoom/SuperCalendar#42]
在DialogFragment中使用该控件，例如:滑动到2017-1月后，结束界面，再次进入，显示当前日期。左右滑动，就跳转到2016-12 或者 2017-2。

**Comment by CodeChild** [comment]
我是在MonthPager这个view里加margin的时候会遇到这bug，把margin去掉就好了

**Comment by MagicMashRoom** [comment]
可能在dialog使用过程中 view没有真正的销毁 所以需要在再次启动起日历的时候进行view的刷新或者数据的刷新
