### ISSUE TITLE
按钮切换时，月份显示不正确

### ISSUE THREAD

**Issue by xiaos1993** [MagicMashRoom/SuperCalendar#48]
点击"下一月"按钮，在点击“今天"或者”更改效果“，最上面的月份显示不正确。例如，今天是8.22，显示的是9.22，而且下面的天数仍是31天。

**Comment by MagicMashRoom** [comment]
重新下DEMO

**Comment by xiaos1993** [comment]
下了还是不行

**Comment by MagicMashRoom** [comment]
我又改了一下 你下载一下DEMO 不要一出问题就问别人 要自己思考思考 其实你要是看过代码 这个问题很好解决
