### ISSUE TITLE
怎么在滑动的时候设置每月的一号为选中？或者每周一选中？

### ISSUE THREAD

**Issue by fenggeZhang** [MagicMashRoom/SuperCalendar#50]

**Comment by MagicMashRoom** [comment]
修改seedDate  如果你认真看过源代码的话

**Comment by ggggxiaolong** [comment]
@MagicMashRoom 
源码的 seedDate 是 private 的  而且 没有相应的 get set 方法，并且在构造方法的时候强行吧seedDate 设置为当天 ，  怎么改？

**Comment by ggggxiaolong** [comment]
@MagicMashRoom  除了反射还有其他的方法吗？
