### ISSUE TITLE
显示月份>=当前月份+2时，回到当前月份卡顿

### ISSUE THREAD

**Issue by loperSeven** [MagicMashRoom/SuperCalendar#53]
monthPager.setCurrentItem(MonthPager.CURRENT_DAY_INDEX); 
博主是有其他实现此功能的方法吗

**Comment by MagicMashRoom** [comment]
使用notify的方式 看看SyllabusActivity中的例子
private void refreshMonthPager() {
        CalendarDate today = new CalendarDate();
        calendarAdapter.notifyDataChanged(today);
        textViewYearDisplay.setText(today.getYear() + "年");
        textViewMonthDisplay.setText(today.getMonth() + "");
    }
