### ISSUE TITLE
怎么去掉当月多余的天数?

### ISSUE THREAD

**Issue by unclebu001** [MagicMashRoom/SuperCalendar#55]
感谢博主分享的demo,很好的用上了..就是在显示月天数可不可以去掉那些当月多余的天数,,看了代码,,无从下手怎么改..求指教

**Comment by MagicMashRoom** [comment]
你可以在custom day view的refreshContent对回调过来的日期判断他的state 如果他不是current_month 的话 你就不让它显示就好了 我已经把所有控制view显示的权限都交给dayview了

**Comment by MagicMashRoom** [comment]
@Override
    public void refreshContent() {
        renderToday(day.getDate());
        renderSelect(day.getState());
        renderMarker(day.getDate(), day.getState());
        super.refreshContent();
    }
在这里可以得到日期的state 看一下源代码 你应该就可以解决这个问题了

**Comment by unclebu001** [comment]
恩恩 感谢博主 今天静心看代码 改好了 还要屏蔽onSelectDateListener的回调函数
