### ISSUE TITLE
支持特定日期 添加图片覆盖吗？

### ISSUE THREAD

**Issue by yanxinmiao** [MagicMashRoom/SuperCalendar#58]
最近要做签到功能，产品给的需求是 已签到的日期用一个图标覆盖，请问支持这个吗 ？

**Comment by yanxinmiao** [comment]
类似这样的效果
![](http://wx1.sinaimg.cn/mw690/6003b141ly1fjgv6031k6j205e04maa0.jpg)

**Comment by awq14789** [comment]
自定义的DayView中可以实现这个功能，在重写的refreshContent方法中可以自己定义

**Comment by yanxinmiao** [comment]
@awq14789 谢谢， 已实现
