### ISSUE TITLE
日历MonthPager的数据超出屏幕右边了

### ISSUE THREAD

**Issue by zhouminxia** [MagicMashRoom/SuperCalendar#60]
日历MonthPager最外面有一层相对布局，并且相对布局paddingstart和paddingend都为10，结果Monthpager显示的左边是正常的，但是右边就超出屏幕了。并且每次左右滑动时，当前页面会有一个向右展开的过程，会让日历超出屏幕右边。
![20170914_164356](https://user-images.githubusercontent.com/17943062/30420459-324c461a-996c-11e7-9c88-38e5e55ad032.jpg)

**Comment by MagicMashRoom** [comment]
你修改customdayview的资源文件的宽度就可以了
