### ISSUE TITLE
当RecyclerView中没有数据时，如何让在一些默认提示文字。

### ISSUE THREAD

**Issue by FaverSoar** [MagicMashRoom/SuperCalendar#61]
MonthPager显示是依据RecyclerView的高来计算的，如果RecyclerView数据为空的时候我需要隐藏RecyclerView来显示一个提示文字的view，这时候日历就无法显示了。大神请问如何能让日历显示呢？

**Comment by MagicMashRoom** [comment]
那你显示一个有高度的TextView咯
