### ISSUE TITLE
滑动的时候怎么给每一页设置默认选中？

### ISSUE THREAD

**Issue by LiHexiang** [MagicMashRoom/SuperCalendar#68]
看到作者的示例图中实现了这个效果，但是下载下来的代码并没有这个效果，求大神解答一下

**Comment by ma969070578** [comment]
CalendarRenderer
修改
  public void update() {
        //设置种子日期为选中
        CalendarViewAdapter.saveDate(seedDate);
        instantiateMonth();
        calendar.invalidate();
    }

**Comment by unclebu001** [comment]
感谢楼上的~我知道要加savDate 就是找不对地方
