### ISSUE TITLE
Mark标记UI刷新问题

### ISSUE THREAD

**Issue by BryanYue** [MagicMashRoom/SuperCalendar#70]
calendarAdapter  调用notifyDataChanged方法传入指定CalendarDate，再调用setMarkData方法，标记UI不刷新，点击或者轻微滑动页面会刷新UI

**Comment by WaterBoss** [comment]
我也遇到这个问题！这个问题处理了吗？

**Comment by ITzhangyan** [comment]
你们解决这个问题了么

**Comment by ma969070578** [comment]
可能是部分手机由于禁用硬件加速，造成的

在调用的Activity 添加 android:hardwareAccelerated="true"

**Comment by voynich-chen** [comment]
我也遇到了这样的问题  获取到的数据 必须点一下其他的  才能刷新标记

**Comment by huangzijie0303** [comment]
这个问题是viewpager adapter 调用notifydatasetchanged 方法不起作用导致的，解决方法一：重写viewpageradapter 的getItemPosition()方法，返回POSITION_NONE,如下：
 @Override
    public int getItemPosition(Object object) {
        return POSITION_NONE;
    },其他方法网上可以搜到的

**Comment by MagicMashRoom** [comment]
先setMarkData在notifyDataChanged

**Comment by qushutong** [comment]
不管用啊 是这样么 
calendarAdapter.setMarkData(markData);
 calendarAdapter.notifyDataSetChanged();

**Comment by FreeLoopC** [comment]
@MagicMashRoom 先setMarkData再notifyDataChanged之后, 左右滑动切换月份就会有问题, 多滑几个月就滑不动了

**Comment by jiang1654** [comment]
@FreeLoopC  兄弟解决了吗？我调用notifyDataChanged之后 直接崩溃了 数组越界
