### ISSUE TITLE
请fork项目的小伙伴重新拉下代码

### ISSUE THREAD

**Issue by MagicMashRoom** [MagicMashRoom/SuperCalendar#8]
Master上的代码被Dev污染 现在已经回退

**Comment by songmao123** [comment]
适配好像有点问题，位置有些错乱。
![preview](http://otbh4av3v.bkt.clouddn.com/device01.png)

**Comment by MagicMashRoom** [comment]
每一个格子的宽度都是你自己定义的  找到你example下的custom_day.xml文件修改宽度就可以了
