### ISSUE TITLE
首先感谢大大的日历解决我的项目的燃眉之急，有个小小的问题，日历上下滑动不是很流畅

### ISSUE THREAD

**Issue by jackyHuangH** [MagicMashRoom/SuperCalendar#80]
开启硬件加速也还是有些卡顿，特别Recyclerview 滑动配合周月切换的时候，看你的GIF图感觉很顺畅，请问有什么方法解决吗？测试机器：小米2，5.0.2

**Comment by wangjiujiu** [comment]
我也想问这个问题，滑动有卡顿，请问有方法解决吗？
