### ISSUE TITLE
#70

### ISSUE THREAD

**Issue by qushutong** [MagicMashRoom/SuperCalendar#86]
mark刷新问题

**Comment by MagicMashRoom** [comment]
/**
     * 初始化标记数据，HashMap的形式，可自定义
     * 如果存在异步的话，在使用setMarkData之后调用 calendarAdapter.notifyDataChanged();
     */
    private void initMarkData() {
        HashMap<String, String> markData = new HashMap<>();
        markData.put("2017-8-9", "1");
        markData.put("2017-7-9", "0");
        markData.put("2017-6-9", "1");
        markData.put("2017-6-10", "0");
        calendarAdapter.setMarkData(markData);
    }
