### ISSUE TITLE
嵌套的recyclerview滑动 有几率会出问题

### ISSUE THREAD

**Issue by SmileChen007** [MagicMashRoom/SuperCalendar#88]
下滑的过程中 recyclerview在某种情况下会反弹上来 然后必须重新把recyclerview 下拉 才能正常使用 
使用的版本是1.4

**Comment by guanjianzhe** [comment]
我也发现了这个问题。

**Comment by NameLessL** [comment]
1.5也有这个问题，概率快速上下滑动会有问题，目前解决了吗

**Comment by SmileChen007** [comment]
感谢刚刚提交的分支，已解决问题
