### ISSUE TITLE
NullPorintException 

### ISSUE THREAD

**Issue by newsolf** [MagicMashRoom/SuperCalendar#90]
在Android 4.3上,要测量Relativelayout 必须要设置宽和高,否则会出现NullPorintException ;

DayView -> refreshContent方法 ,添加 
setLayoutParams(new LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT));

**Comment by daoxiaomianzi** [comment]
这个好像是低版本Relativelayout的bug，我也遇到改过了

**Comment by MagicMashRoom** [comment]
谢谢小伙伴的参与 可以把修改的代码以PR的形式上传项目
