### ISSUE TITLE
设置星期日开头吐槽

### ISSUE THREAD

**Issue by FreeLoopC** [MagicMashRoom/SuperCalendar#97]
为了设置星期日开头
查了一下源码, 终于在CalendarAttr类中找到WeekArrayType枚举设置星期日开头,
修改后发现并没有什么变化, 还以为没有实现这个功能
然后翻查github issues 总算在CalendarViewAdapter找到了weekArrayType, 修改此值, 成功
这里吐槽一下, 这个weekArrayType一会儿是枚举值, 一会儿又是int值
感觉代码像是多个人写的, 每个人又有每个人自己的写法, 太误导人了, 希望修正一下

**Comment by MagicMashRoom** [comment]
修正了
