### ISSUE TITLE
Failed to resolve:

### ISSUE THREAD

**Issue by 957919019** [MagicMashRoom/SuperCalendar#99]
build

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

    compile 'com.github.MagicMashRoom:SuperCalendar:v1.4.2'

but it doesn't work on my machine

Error:(36, 13) Failed to resolve: com.github.MagicMashRoom:SuperCalendar:v1.4.2

**Comment by MagicMashRoom** [comment]
you can download project to you computer, jitpack have some problem now
